{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a7cd4840-ba37-41e1-8e79-eb26ef328810",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from sklearn.preprocessing import OneHotEncoder\n",
    "def dynamic_preprocessor(path, target_col):\n",
    "    churn_df=pd.read_csv(path)\n",
    "    churn_df = churn_df.apply(lambda x: x.str.strip() if x.dtype == \"object\" else x)\n",
    "    for col in churn_df.columns:\n",
    "        if churn_df[col].dtype == \"object\":\n",
    "            converted = pd.to_numeric(churn_df[col], errors=\"coerce\")\n",
    "    \n",
    "            # convert if most values are numeric\n",
    "            if converted.notna().sum() / len(churn_df) > 0.8:\n",
    "                churn_df[col] = converted\n",
    "        \n",
    "        missing_ratio = churn_df[col].isnull().mean()\n",
    "        if missing_ratio < 0.025:\n",
    "            churn_df = churn_df[churn_df[col].notnull()]\n",
    "        else:\n",
    "            if churn_df[col].dtype in [\"int64\",\"float64\"]:\n",
    "                churn_df[col] = churn_df[col].fillna(churn_df[col].median())\n",
    "            else:\n",
    "                churn_df[col] = churn_df[col].fillna(churn_df[col].mode()[0])\n",
    "        \n",
    "        cols_to_drop = []\n",
    "        if col != target_col:\n",
    "            unique_ratio = churn_df[col].nunique() / len(churn_df)\n",
    "            \n",
    "            if unique_ratio > 0.95:\n",
    "                cols_to_drop.append(col)\n",
    "        churn_df = churn_df.drop(columns=cols_to_drop)\n",
    "    inputs = churn_df.drop(columns=[target_col])\n",
    "    target = churn_df[target_col]\n",
    "    numeric_cols=inputs.select_dtypes(include=[\"int64\", \"float64\"]).columns\n",
    "    categorical_cols=inputs.select_dtypes(include=[\"object\"]).columns\n",
    "\n",
    "    binary_cols = [\n",
    "        col for col in categorical_cols\n",
    "        if inputs[col].nunique() == 2\n",
    "    ]\n",
    "    for col in binary_cols:\n",
    "        unique_vals = inputs[col].dropna().unique()\n",
    "        inputs[col] = inputs[col].replace({unique_vals[0]:1, unique_vals[1]:0})\n",
    "    \n",
    "    multiple_cols = [\n",
    "        col for col in categorical_cols\n",
    "        if inputs[col].nunique() > 2\n",
    "    ]\n",
    "    \n",
    "    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')\n",
    "    encoded_dfs = []\n",
    "    for col in multiple_cols:\n",
    "        encoded = encoder.fit_transform(inputs[[col]])\n",
    "        encoded_df = pd.DataFrame(\n",
    "            encoded,\n",
    "            columns=encoder.get_feature_names_out([col]),\n",
    "            index=inputs.index\n",
    "        )\n",
    "        encoded_dfs.append(encoded_df)\n",
    "    encoded_all = pd.concat(encoded_dfs, axis=1)\n",
    "    inputs = inputs.drop(columns=multiple_cols)\n",
    "    inputs = pd.concat([inputs, encoded_all], axis=1)\n",
    "    print(\"Preprocesing is done!\")\n",
    "    return inputs, target"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d5ccd0c4-2c79-4313-9d77-e7f86ed9bc5b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Preprocesing is done!\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "(       age  default  balance  housing  loan  day  duration  campaign  pdays  \\\n",
       " 0       59        1     2343        1     1    5      1042         1     -1   \n",
       " 1       56        1       45        0     1    5      1467         1     -1   \n",
       " 2       41        1     1270        1     1    5      1389         1     -1   \n",
       " 3       55        1     2476        1     1    5       579         1     -1   \n",
       " 4       54        1      184        0     1    5       673         2     -1   \n",
       " ...    ...      ...      ...      ...   ...  ...       ...       ...    ...   \n",
       " 11157   33        1        1        1     1   20       257         1     -1   \n",
       " 11158   39        1      733        0     1   16        83         4     -1   \n",
       " 11159   32        1       29        0     1   19       156         2     -1   \n",
       " 11160   43        1        0        0     0    8         9         2    172   \n",
       " 11161   34        1        0        0     1    9       628         1     -1   \n",
       " \n",
       "        previous  ...  month_jun  month_mar  month_may  month_nov  month_oct  \\\n",
       " 0             0  ...        0.0        0.0        1.0        0.0        0.0   \n",
       " 1             0  ...        0.0        0.0        1.0        0.0        0.0   \n",
       " 2             0  ...        0.0        0.0        1.0        0.0        0.0   \n",
       " 3             0  ...        0.0        0.0        1.0        0.0        0.0   \n",
       " 4             0  ...        0.0        0.0        1.0        0.0        0.0   \n",
       " ...         ...  ...        ...        ...        ...        ...        ...   \n",
       " 11157         0  ...        0.0        0.0        0.0        0.0        0.0   \n",
       " 11158         0  ...        1.0        0.0        0.0        0.0        0.0   \n",
       " 11159         0  ...        0.0        0.0        0.0        0.0        0.0   \n",
       " 11160         5  ...        0.0        0.0        1.0        0.0        0.0   \n",
       " 11161         0  ...        0.0        0.0        0.0        0.0        0.0   \n",
       " \n",
       "        month_sep  poutcome_failure  poutcome_other  poutcome_success  \\\n",
       " 0            0.0               0.0             0.0               0.0   \n",
       " 1            0.0               0.0             0.0               0.0   \n",
       " 2            0.0               0.0             0.0               0.0   \n",
       " 3            0.0               0.0             0.0               0.0   \n",
       " 4            0.0               0.0             0.0               0.0   \n",
       " ...          ...               ...             ...               ...   \n",
       " 11157        0.0               0.0             0.0               0.0   \n",
       " 11158        0.0               0.0             0.0               0.0   \n",
       " 11159        0.0               0.0             0.0               0.0   \n",
       " 11160        0.0               1.0             0.0               0.0   \n",
       " 11161        0.0               0.0             0.0               0.0   \n",
       " \n",
       "        poutcome_unknown  \n",
       " 0                   1.0  \n",
       " 1                   1.0  \n",
       " 2                   1.0  \n",
       " 3                   1.0  \n",
       " 4                   1.0  \n",
       " ...                 ...  \n",
       " 11157               1.0  \n",
       " 11158               1.0  \n",
       " 11159               1.0  \n",
       " 11160               0.0  \n",
       " 11161               1.0  \n",
       " \n",
       " [11162 rows x 48 columns],\n",
       " 0        yes\n",
       " 1        yes\n",
       " 2        yes\n",
       " 3        yes\n",
       " 4        yes\n",
       "         ... \n",
       " 11157     no\n",
       " 11158     no\n",
       " 11159     no\n",
       " 11160     no\n",
       " 11161     no\n",
       " Name: deposit, Length: 11162, dtype: object)"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dynamic_preprocessor(\"../data/bank_marketing.csv\", \"deposit\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1b86f605-783c-4716-b2fe-d5f9d6dfd5e7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
